const token=location.hash.slice(1)||sessionStorage.getItem('lanternToken')||'';if(token)sessionStorage.setItem('lanternToken',token);history.replaceState(null,'',location.pathname);
const $=id=>document.getElementById(id); let latest=null, stopped=false, rendered='', currentPlan=null; const selected=new Set();
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'X-Lantern-Token':token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}
function detail(target,title,data){const d=el('details');d.append(el('summary',title),el('pre',JSON.stringify(data,null,2)));target.append(d);}
function table(target,headers,rows){target.replaceChildren();const t=el('table'),head=el('tr');headers.forEach(x=>head.append(el('th',x)));t.append(head);rows.forEach(row=>{const tr=el('tr');row.forEach(v=>tr.append(el('td',String(v??'—'))));t.append(tr)});target.append(t);}
function renderLogs(){const entries=latest?.report?.collectors.logs?.data?.entries||[];const q=$('filter').value.toLowerCase();$('logs').replaceChildren();entries.filter(e=>JSON.stringify(e).toLowerCase().includes(q)).forEach(e=>detail($('logs'),`${e.level} · ${e.source} · ${e.message.slice(0,110)}`,e));}
function render(s){latest=s;$('status').textContent=s.status;$('notice').textContent=s.error||'';const busy=['collecting','discovering','repairing'].includes(s.status);['refresh','discover','fix-selected','fix-all'].forEach(id=>$(id).disabled=busy);$('stop').disabled=s.status==='repairing';renderRepair(s.repair);renderResearch(s.research);if(!s.report)return;
updateRepairButtons();const key=JSON.stringify(s);if(key===rendered)return;rendered=key;const r=s.report,c=r.collectors,sys=c.system?.data||{};renderGuideOptions(r.guides||[]);
$('summary').replaceChildren();[['Device',sys.hostname||'Unavailable'],['Operating system',sys.os||'Unavailable'],['Memory used',sys.memory?Math.round(sys.memory.percent)+'%':'Unavailable'],['Collection',r.privilege]].forEach(([k,v])=>{const d=el('div',k,'metric');d.append(el('strong',v));$('summary').append(d)});
$('findings').replaceChildren();if(!r.findings.length)$('findings').append(el('p','No known diagnostic patterns matched. Review logs and coverage below.'));
r.findings.forEach(f=>{const d=el('article',undefined,'finding '+f.severity);d.append(el('span',f.importance||'Worth checking','badge'),el('h3',f.title),el('p',f.plain_explanation||f.likely_cause));if($('humor').checked&&f.humor)d.append(el('p',f.humor,'joke'));if(f.repair){const label=el('label'),check=el('input');check.type='checkbox';check.checked=selected.has(f.id);check.disabled=busy;check.onchange=()=>{check.checked?selected.add(f.id):selected.delete(f.id);updateRepairButtons()};label.append(check,document.createTextNode(' Include this item'));const fix=el('button','Fix this');fix.disabled=busy;fix.onclick=()=>reviewRepairs([f.id]);d.append(label,fix)}else{const next=el('button','Show next steps'),guide=el('p',f.suggestion);guide.hidden=true;next.onclick=()=>{guide.hidden=!guide.hidden;next.textContent=guide.hidden?'Show next steps':'Hide next steps'};d.append(next,guide)}detail(d,'Technical details · '+f.confidence,f.evidence);$('findings').append(d)});updateRepairButtons();
$('networks').textContent='Connected private networks: '+(r.networks.join(', ')||'None detected');if(!$('cidr').value&&r.networks.length)$('cidr').value=r.networks[0];
$('map').replaceChildren();const self=el('div',undefined,'device');self.append(el('strong',sys.hostname||'This device'),el('p','This device → directly connected local network'));$('map').append(self);const devices=new Map();[...(c.neighbors?.data||[]),...s.discovery].forEach(d=>devices.set(d.ip,d));devices.forEach(d=>{const n=el('div',undefined,'device');n.append(el('strong',d.ip),el('p',d.evidence),el('p',d.services.map(x=>`${x.port} ${x.label} (inferred)`).join(', ')||'No service probes recorded'));$('map').append(n)});
$('coverage').replaceChildren();(c.logs?.data?.coverage||[]).forEach(x=>$('coverage').append(el('p',`${x.source}: ${x.status} — ${x.limit||x.detail}`)));renderLogs();
const ep=a=>a?`${a.ip}:${a.port}`:'—';table($('connections'),['Protocol','Local','Remote','State','PID'],(c.connections?.data?.items||[]).map(x=>[x.transport,ep(x.local),ep(x.remote),x.status,x.pid]));
$('details').replaceChildren();Object.entries(c).forEach(([name,value])=>detail($('details'),`${name} · ${value.status}`,value));renderExtensions(s);}
async function action(path,body={}){try{await api(path,body);rendered='';await poll()}catch(e){$('notice').textContent=e.message}}
$('refresh').onclick=()=>action('refresh');$('discover').onclick=()=>{if(!$('consent').checked){$('notice').textContent='Check the authorization box before discovery.';return}action('discover',{cidr:$('cidr').value.trim(),consent:true})};
$('stop').onclick=async()=>{try{await api('stop',{});stopped=true;$('status').textContent='Stopped';document.querySelectorAll('button').forEach(b=>b.disabled=true)}catch(e){$('notice').textContent=e.message}};
$('export').onclick=()=>{if(!latest?.report)return;const blob=new Blob([JSON.stringify(latest,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='lantern-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('filter').oninput=renderLogs;async function poll(){if(stopped)return;try{render(await api('state'))}catch(e){$('notice').textContent='Agent unavailable: '+e.message}}poll();setInterval(poll,2000);

function repairable(){return (latest?.report?.findings||[]).filter(f=>f.repair)}
function updateRepairButtons(){const available=repairable(),ids=new Set(available.map(f=>f.id));for(const id of selected)if(!ids.has(id))selected.delete(id);const busy=latest?.status!=='ready';$('fix-all').disabled=busy||!available.length;$('fix-selected').disabled=busy||!selected.size}
async function reviewRepairs(ids){try{currentPlan=await api('repair-plan',{ids});$('repair-plan').replaceChildren(el('p',currentPlan.warning));currentPlan.items.forEach(item=>{const d=el('div',undefined,'plan-item');d.append(el('h3',item.label),el('p',item.change),el('p',item.impact),el('p',item.backup),el('p','Undo limits: '+item.undo));$('repair-plan').append(d)});$('repair-consent').checked=false;$('repair-confirm').disabled=true;$('repair-error').textContent='';$('repair-dialog').showModal()}catch(e){$('notice').textContent=e.message}}
$('fix-selected').onclick=()=>reviewRepairs([...selected]);$('fix-all').onclick=()=>reviewRepairs(repairable().map(f=>f.id));$('repair-cancel').onclick=()=>$('repair-dialog').close();$('repair-consent').onchange=()=>$('repair-confirm').disabled=!$('repair-consent').checked;
$('repair-confirm').onclick=async()=>{if(!currentPlan||!$('repair-consent').checked)return;$('repair-confirm').disabled=true;try{await api('repair-approve',{plan_id:currentPlan.id,consent:true});$('repair-dialog').close();currentPlan=null;selected.clear();await poll()}catch(e){$('repair-error').textContent=e.message;$('repair-confirm').disabled=false}};
$('humor').onchange=()=>{rendered='';if(latest)render(latest)};
function renderRepair(repair){$('repair-progress').hidden=!repair;if(!repair)return;const box=$('repair-status');box.replaceChildren(el('h3',({permission:'Permission',backing_up:'Backing up',repairing:'Repairing',verifying:'Checking the result',complete:'Finished',failed:'Needs attention'})[repair.stage]||repair.stage),el('p',repair.message));if(repair.backup)box.append(el('p','Service-state backup: '+repair.backup));(repair.results||[]).forEach(r=>{box.append(el('h3',r.label+' — '+r.status),el('p',r.detail))});if(['complete','failed'].includes(repair.stage)){const refresh=el('button','Check my device again');refresh.onclick=()=>action('refresh');box.append(refresh)}}
function renderGuideOptions(guides){const choice=$('symptom').value;const first=el('option','Choose a problem');first.value='';$('symptom').replaceChildren(first);guides.forEach(g=>{const option=el('option',g.title);option.value=g.id;$('symptom').append(option)});$('symptom').value=choice;renderGuide()}
function renderGuide(){const g=latest?.report?.guides?.find(x=>x.id===$('symptom').value),box=$('symptom-guide');box.replaceChildren();if(!g)return;box.append(el('h3',g.title));if($('humor').checked)box.append(el('p',g.joke,'joke'));const steps=el('ol');g.steps.forEach(step=>steps.append(el('li',step)));box.append(steps,el('p','How to check it worked: '+g.verify));if(g.url){const a=el('a','Open official support instructions');a.href=g.url;a.target='_blank';a.rel='noopener noreferrer';box.append(a)}if(g.id==='drivers'){const health=latest.report.collectors.device_health?.data;box.append(el('p',health?.driver_updates?.status==='cached_only'?'Driver-update information is from the saved Windows Update list. Check Windows Update for current availability.':'Current driver-update availability is unknown. An older driver date alone does not mean it needs replacement.'));if(health?.problem_devices?.length)detail(box,'Devices reporting a problem',health.problem_devices);if(health?.installed_drivers)detail(box,'Installed driver details',health.installed_drivers)}}
$('symptom').onchange=renderGuide;

let researchId=null, walkIndex=0, walking=false;
function renderExtensions(s){
 const i=s.report.insights||{},box=$('insights');box.replaceChildren();
 box.append(el('p',i.baseline_saved_at?'Working baseline saved: '+i.baseline_saved_at:'No working baseline saved. Save one when your device is working the way you expect.'));
 if(s.report.baseline_error)box.append(el('p',s.report.baseline_error));
 const groups=i.grouped_logs||{events:0,groups:[]};box.append(el('p',`${groups.events} collected log messages grouped into ${groups.groups.length} displayed patterns. Similar messages do not necessarily share a cause.`));
 detail(box,'Repeated log patterns',groups.groups);groups.groups.slice(0,10).forEach((group,index)=>{const row=el('p',`${group.count} messages · ${group.source} `),research=el('button','Ask AI about this pattern');research.onclick=()=>openResearch('log-group:'+index);row.append(research);box.append(row)});detail(box,'Changes since the last check',i.since_last_check||[]);detail(box,'Changes since your working baseline',i.since_working_baseline||[]);
 [...$('findings').children].forEach((card,index)=>{const f=s.report.findings[index];if(!f)return;card.prepend(el('p',f.disposition||'Needs review','badge'));if(!f.repair){const b=el('button','Ask AI for help');b.onclick=()=>openResearch(f.id);card.append(b)}});
 $('repair-history').replaceChildren();if(!s.history.length)$('repair-history').append(el('p','No repairs have run in this session.'));
 s.history.forEach(record=>{const d=el('article');d.append(el('h3',record.at+' · '+record.stage),el('p','Your result: '+record.feedback));detail(d,'Repair results',record.results);const undo=el('details');undo.append(el('summary','Undo options'),el('p',record.undo));d.append(undo);['It works now','Still broken','Not tested'].forEach(answer=>{const b=el('button',answer);b.onclick=()=>action('repair-feedback',{id:record.id,feedback:answer});d.append(b)});$('repair-history').append(d)});
 const media=$('media-devices');media.replaceChildren();if(s.media){media.append(el('p',s.media.note));if(!s.media.devices.length)media.append(el('p','No supported advertisements received. This does not prove there are no TVs nearby.'));s.media.devices.forEach(device=>{const card=el('article',undefined,'device');card.append(el('h3',device.kind+' · '+device.ip),el('p',device.confidence),el('p',device.casting));detail(card,'Advertised software',device.advertised_software);const steps=el('details'),list=el('ol');steps.append(el('summary','How to use this device'));device.steps.forEach(step=>list.append(el('li',step)));steps.append(list);const a=el('a','Official Google Cast instructions');a.href=device.help_url;a.target='_blank';a.rel='noopener noreferrer';steps.append(a);card.append(steps);media.append(card)});detail(media,'Discovery coverage',s.media.coverage)}
 ['save-baseline','forget-baseline','media-discover'].forEach(id=>$(id).disabled=s.status!=='ready');
}
$('save-baseline').onclick=()=>{if(confirm('Save OS version, driver names/versions, service states, disk-use percentages and finding counts locally as your working baseline? Raw logs, hostnames and network addresses are omitted.'))action('baseline-save',{consent:true})};
$('forget-baseline').onclick=()=>{if(confirm('Remove only the saved Lantern working baseline?'))action('baseline-forget',{consent:true})};
$('media-discover').onclick=()=>{if(!$('media-consent').checked){$('notice').textContent='Allow local media-discovery messages first.';return}action('media-discover',{consent:true})};
function showPacket(text,title){$('research-send').hidden=!researchId;$('support-download').hidden=!!researchId;$('support-title').textContent=title;$('support-text').value=text;$('support-dialog').showModal()}
$('support-report').onclick=async()=>{try{researchId=null;$('research-details-label').hidden=true;const packet=await api('support-summary');showPacket(packet.text,'Review your support report')}catch(e){$('notice').textContent=e.message}};
async function openResearch(id){try{researchId=id;$('research-details-label').hidden=false;$('research-details').checked=false;const packet=await api('research-packet',{id});showPacket(packet.text,'Ask AI for help — review before sending')}catch(e){$('notice').textContent=e.message}}
$('research-details').onchange=async()=>{if(!researchId)return;if(!confirm('Replace the current draft with a newly generated summary? Any edits in this box will be replaced.')){$('research-details').checked=!$('research-details').checked;return}try{const packet=await api('research-packet',{id:researchId,include_details:$('research-details').checked});$('support-text').value=packet.text}catch(e){$('notice').textContent=e.message}};
$('support-close').onclick=()=>$('support-dialog').close();
$('support-download').onclick=()=>{const blob=new Blob([$('support-text').value],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=researchId?'lantern-research-request.txt':'lantern-support-summary.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('test-sound').onclick=async()=>{try{const context=new AudioContext();await context.resume();const oscillator=context.createOscillator(),gain=context.createGain();gain.gain.value=.02;oscillator.frequency.value=440;oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.4);oscillator.onended=()=>context.close();$('sound-result').textContent='Did you hear it through the intended speaker or headset? Hearing it confirms this browser can play sound, not every app.'}catch(e){$('sound-result').textContent='The browser could not play a test tone: '+e.message}};
function walk(){const guide=latest?.report?.guides?.find(g=>g.id===$('symptom').value),box=$('walkthrough');box.replaceChildren();if(!guide){box.append(el('p','Choose a problem above, then use the step-by-step helper.'));return}box.append(el('h3','Walk me through: '+guide.title));if(!walking){const start=el('button','Walk me through it');start.onclick=()=>{walking=true;walkIndex=0;walk()};box.append(start);return}if(walkIndex>=guide.steps.length){box.append(el('p',guide.verify),el('p','Still stuck? Use Ask AI for help on the related finding.'));return}box.append(el('p',`Step ${walkIndex+1} of ${guide.steps.length}`),el('p',guide.steps[walkIndex]));const next=el('button','Still stuck — next step'),done=el('button','That worked');next.onclick=()=>{walkIndex++;walk()};done.onclick=()=>{box.replaceChildren(el('p','Good—repeat the original task once more to confirm. No additional repairs will run.'))};box.append(next,done)}
$('symptom').onchange=()=>{renderGuide();walking=false;walkIndex=0;walk()};walk();

$('research-send').onclick=async()=>{try{await api('research-start',{text:$('support-text').value,consent:true});$('support-dialog').close();await poll();$('research-result').scrollIntoView({behavior:'smooth'})}catch(e){$('support-title').textContent=e.message}};
function renderResearch(r){const box=$('research-result');if(!r)return;box.replaceChildren();if(!r.configured){box.append(el('p','AI research is not connected yet. The app operator needs to configure the hosted service.'));return}if(r.status==='idle'){box.append(el('p','Research service: '+r.service+'. Choose Ask AI for help on an issue.'));return}if(r.status==='running'){box.append(el('p','Researching your reviewed summary. You can keep using the app; no repairs are running from this request.'));return}if(r.status==='failed'){box.append(el('p',r.error));return}box.append(el('p','AI research suggestions — check that they match your symptoms. No changes have been made.'));for(const part of r.result?.parts||[]){if(typeof part.text!=='string')continue;const p=el('p');p.style.whiteSpace='pre-wrap';let cursor=0;const citations=(part.citations||[]).filter(c=>Number.isInteger(c.start_index)&&Number.isInteger(c.end_index)&&c.start_index>=0&&c.end_index<=part.text.length&&c.end_index>c.start_index).sort((a,b)=>a.start_index-b.start_index);for(const c of citations){let u;try{u=new URL(c.url)}catch{continue}if(u.protocol!=='https:'||u.username||u.password||c.start_index<cursor)continue;p.append(document.createTextNode(part.text.slice(cursor,c.start_index)));const a=el('a',part.text.slice(c.start_index,c.end_index)||c.title);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';p.append(a);cursor=c.end_index}p.append(document.createTextNode(part.text.slice(cursor)));box.append(p)}}
